import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Test from "./Test";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex justify-end h-[100%] ">
            <div className="w-[259px] bg-white p-4 ">
              {children}
            </div>
          </div>
        </body>
      </html>
    </>
  );
}
